//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavisca.Common.Plugins.Configuration {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FaultCodes() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tavisca.Common.Plugins.Configuration.FaultCodes", typeof(FaultCodes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 297.
        /// </summary>
        public static string ConfigurationValueReadFailed {
            get {
                return ResourceManager.GetString("ConfigurationValueReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 296.
        /// </summary>
        public static string ConsulConfigurationClientNotAvailable {
            get {
                return ResourceManager.GetString("ConsulConfigurationClientNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 298.
        /// </summary>
        public static string FailedToDecodePayloadInConfigurationClient {
            get {
                return ResourceManager.GetString("FailedToDecodePayloadInConfigurationClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 293.
        /// </summary>
        public static string InvalidDataFromEvents {
            get {
                return ResourceManager.GetString("InvalidDataFromEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 294.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 295.
        /// </summary>
        public static string NoConfigurationProviderOrSerializer {
            get {
                return ResourceManager.GetString("NoConfigurationProviderOrSerializer", resourceCulture);
            }
        }
    }
}
