//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavisca.Configuration.Service
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValue", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.Configuration.Service")]
    [System.SerializableAttribute()]
    public partial class KeyValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://tavisca.configuration.service", ConfigurationName="IConfigurationService")]
public interface IConfigurationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tavisca.configuration.service/IConfigurationService/Get", ReplyAction="http://tavisca.configuration.service/IConfigurationService/GetResponse")]
    string Get(string scope, string applicationName, string section, string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tavisca.configuration.service/IConfigurationService/Get", ReplyAction="http://tavisca.configuration.service/IConfigurationService/GetResponse")]
    System.Threading.Tasks.Task<string> GetAsync(string scope, string applicationName, string section, string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tavisca.configuration.service/IConfigurationService/Update", ReplyAction="http://tavisca.configuration.service/IConfigurationService/UpdateResponse")]
    void Update(System.Collections.Generic.List<Tavisca.Configuration.Service.KeyValue> dataSet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tavisca.configuration.service/IConfigurationService/Update", ReplyAction="http://tavisca.configuration.service/IConfigurationService/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(System.Collections.Generic.List<Tavisca.Configuration.Service.KeyValue> dataSet);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IConfigurationServiceChannel : IConfigurationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<IConfigurationService>, IConfigurationService
{
    
    public ConfigurationServiceClient()
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Get(string scope, string applicationName, string section, string key)
    {
        return base.Channel.Get(scope, applicationName, section, key);
    }
    
    public System.Threading.Tasks.Task<string> GetAsync(string scope, string applicationName, string section, string key)
    {
        return base.Channel.GetAsync(scope, applicationName, section, key);
    }
    
    public void Update(System.Collections.Generic.List<Tavisca.Configuration.Service.KeyValue> dataSet)
    {
        base.Channel.Update(dataSet);
    }
    
    public System.Threading.Tasks.Task UpdateAsync(System.Collections.Generic.List<Tavisca.Configuration.Service.KeyValue> dataSet)
    {
        return base.Channel.UpdateAsync(dataSet);
    }
}
